openapi: "3.0.0"
info:
  title: Share Play
  description: Share Play api for watching videos together
  version: "0.1"
paths:
  /:
    get:
      summary: Returns share-play api info
      responses:
        200:
          description: Returns share-play api info
          content:
            application/json:
              schema:
                type: object
                properties:
                  api:
                    type: string
                  version:
                    type: number
  /add:
    post:
      summary: Add a video file to serve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filepath:
                  type: string
      responses:
        200:
          description: Returns the checksum of the file
          content:
            application/json:
              schema:
                type: object
                properties:
                  checksum:
                    type: string
                  filepath:
                    type: string
                  lastModified:
                    type: string